extends Node


# 发展卡数据, "cost"中对应颜色顺序为"white", "blue", "green", "red", "brown"


export var PRIMARY_CARD_DATA = {
	"0": {"score": 0, "color": "red", "cost": [3, 0, 0, 0, 0]},                                            
	"1": {"score": 0, "color": "red", "cost": [2, 1, 1, 0, 1]},                                            
	"2": {"score": 0, "color": "white", "cost": [0, 0, 0, 2, 1]},                                            
	"3": {"score": 0, "color": "white", "cost": [0, 1, 1, 1, 1]},                                            
	"4": {"score": 0, "color": "white", "cost": [3, 1, 0, 0, 1]},                                            
	"5": {"score": 0, "color": "green", "cost": [1, 1, 0, 1, 2]},                                            
	"6": {"score": 0, "color": "green", "cost": [2, 1, 0, 0, 0]},                                            
	"7": {"score": 0, "color": "blue", "cost": [1, 0, 0, 0, 2]},                                            
	"8": {"score": 0, "color": "brown", "cost": [0, 0, 3, 0, 0]},                                            
	"9": {"score": 0, "color": "brown", "cost": [1, 2, 1, 1, 0]},                                            
	"10": {"score": 0, "color": "white", "cost": [0, 1, 2, 1, 1]},                                           
	"11": {"score": 0, "color": "white", "cost": [0, 2, 0, 0, 2]},                                           
	"12": {"score": 1, "color": "blue", "cost": [0, 0, 0, 4, 0]},                                           
	"13": {"score": 0, "color": "blue", "cost": [0, 0, 2, 0, 2]},                                           
	"14": {"score": 0, "color": "blue", "cost": [1, 0, 1, 1, 1]},                                           
	"15": {"score": 0, "color": "brown", "cost": [2, 2, 0, 1, 0]},                                           
	"16": {"score": 1, "color": "brown", "cost": [0, 4, 0, 0, 0]},                                           
	"17": {"score": 0, "color": "brown", "cost": [0, 0, 2, 1, 0]},                                           
	"18": {"score": 1, "color": "red", "cost": [4, 0, 0, 0, 0]},                                           
	"19": {"score": 0, "color": "green", "cost": [0, 1, 0, 2, 2]},                                           
	"20": {"score": 0, "color": "green", "cost": [1, 3, 1, 0, 0]},                                           
	"21": {"score": 0, "color": "green", "cost": [0, 0, 0, 3, 0]},                                           
	"22": {"score": 1, "color": "white", "cost": [0, 0, 4, 0, 0]},                                           
	"23": {"score": 0, "color": "red", "cost": [1, 1, 1, 0, 1]},                                           
	"24": {"score": 0, "color": "blue", "cost": [1, 0, 1, 2, 1]},                                           
	"25": {"score": 0, "color": "blue", "cost": [0, 1, 3, 1, 0]},                                           
	"26": {"score": 0, "color": "green", "cost": [1, 1, 0, 1, 1]},                                           
	"27": {"score": 0, "color": "green", "cost": [0, 2, 0, 2, 0]},                                           
	"28": {"score": 1, "color": "green", "cost": [0, 0, 0, 0, 4]},                                           
	"29": {"score": 0, "color": "blue", "cost": [1, 0, 2, 2, 0]},                                           
	"30": {"score": 0, "color": "blue", "cost": [0, 0, 0, 0, 3]},                                           
	"31": {"score": 0, "color": "white", "cost": [0, 3, 0, 0, 0]},                                           
	"32": {"score": 0, "color": "white", "cost": [0, 2, 2, 0, 1]},                                           
	"33": {"score": 0, "color": "red", "cost": [1, 0, 0, 1, 3]},                                           
	"34": {"score": 0, "color": "red", "cost": [0, 2, 1, 0, 0]},                                           
	"35": {"score": 0, "color": "red", "cost": [2, 0, 1, 0, 2]},                                           
	"36": {"score": 0, "color": "brown", "cost": [2, 0, 2, 0, 0]},                                           
	"37": {"score": 0, "color": "brown", "cost": [1, 1, 1, 1, 0]},                                           
	"38": {"score": 0, "color": "brown", "cost": [0, 0, 1, 3, 1]},                                           
	"39": {"score": 0, "color": "red", "cost": [2, 0, 0, 2, 0]}
}


export var JUNIOR_CARD_DATA = {
	"0": {"score": 2, "color": "red", "cost": [3, 0, 0, 0, 5]},                                           
	"1": {"score": 3, "color": "blue", "cost": [0, 6, 0, 0, 0]},                                           
	"2": {"score": 3, "color": "green", "cost": [0, 0, 6, 0, 0]},                                           
	"3": {"score": 3, "color": "white", "cost": [6, 0, 0, 0, 0]},                                           
	"4": {"score": 1, "color": "brown", "cost": [3, 0, 3, 0, 2]},                                           
	"5": {"score": 2, "color": "green", "cost": [0, 0, 5, 0, 0]},                                           
	"6": {"score": 2, "color": "brown", "cost": [0, 0, 5, 3, 0]},                                           
	"7": {"score": 1, "color": "red", "cost": [2, 0, 0, 2, 3]},                                           
	"8": {"score": 2, "color": "brown", "cost": [0, 1, 4, 2, 0]},                                           
	"9": {"score": 1, "color": "green", "cost": [3, 0, 2, 3, 0]},                                           
	"10": {"score": 2, "color": "white", "cost": [0, 0, 0, 5, 0]},                                          
	"11": {"score": 3, "color": "red", "cost": [0, 0, 0, 6, 0]},                                          
	"12": {"score": 2, "color": "white", "cost": [0, 0, 1, 4, 2]},                                          
	"13": {"score": 2, "color": "red", "cost": [0, 0, 0, 0, 5]},                                          
	"14": {"score": 1, "color": "white", "cost": [0, 0, 3, 2, 2]},                                          
	"15": {"score": 2, "color": "green", "cost": [4, 2, 0, 0, 1]},                                          
	"16": {"score": 2, "color": "blue", "cost": [5, 3, 0, 0, 0]},                                          
	"17": {"score": 3, "color": "brown", "cost": [0, 0, 0, 0, 6]},                                          
	"18": {"score": 2, "color": "green", "cost": [0, 5, 3, 0, 0]},                                          
	"19": {"score": 1, "color": "blue", "cost": [0, 2, 3, 0, 3]},                                          
	"20": {"score": 2, "color": "brown", "cost": [5, 0, 0, 0, 0]},                                          
	"21": {"score": 2, "color": "blue", "cost": [2, 0, 0, 1, 4]},                                          
	"22": {"score": 1, "color": "blue", "cost": [0, 2, 2, 3, 0]},                                          
	"23": {"score": 2, "color": "white", "cost": [0, 0, 0, 5, 3]},                                          
	"24": {"score": 1, "color": "white", "cost": [2, 3, 0, 3, 0]},                                          
	"25": {"score": 2, "color": "red", "cost": [1, 4, 2, 0, 0]},                                          
	"26": {"score": 1, "color": "brown", "cost": [3, 2, 2, 0, 0]},                                          
	"27": {"score": 1, "color": "red", "cost": [0, 3, 0, 2, 3]},                                          
	"28": {"score": 2, "color": "blue", "cost": [0, 5, 0, 0, 0]},                                          
	"29": {"score": 1, "color": "green", "cost": [2, 3, 0, 0, 2]}
}


export var SENIOR_CARD_DATA = {
	"0": {"score": 4, "color": "brown", "cost": [0, 0, 0, 7, 0]},                                           
	"1": {"score": 5, "color": "red", "cost": [0, 0, 7, 3, 0]},                                           
	"2": {"score": 4, "color": "green", "cost": [0, 7, 0, 0, 0]},                                           
	"3": {"score": 4, "color": "white", "cost": [3, 0, 0, 3, 6]},                                           
	"4": {"score": 3, "color": "brown", "cost": [3, 3, 5, 3, 0]},                                           
	"5": {"score": 4, "color": "brown", "cost": [0, 0, 3, 6, 3]},                                           
	"6": {"score": 4, "color": "white", "cost": [0, 0, 0, 0, 7]},                                           
	"7": {"score": 4, "color": "green", "cost": [3, 6, 3, 0, 0]},                                           
	"8": {"score": 5, "color": "blue", "cost": [7, 3, 0, 0, 0]},                                           
	"9": {"score": 4, "color": "red", "cost": [0, 3, 6, 3, 0]},                                           
	"10": {"score": 4, "color": "red", "cost": [0, 0, 7, 0, 0]},                                          
	"11": {"score": 5, "color": "brown", "cost": [0, 0, 0, 7, 3]},                                          
	"12": {"score": 5, "color": "green", "cost": [0, 7, 3, 0, 0]},                                          
	"13": {"score": 3, "color": "green", "cost": [5, 3, 0, 3, 3]},                                          
	"14": {"score": 4, "color": "blue", "cost": [6, 3, 0, 0, 3]},                                          
	"15": {"score": 5, "color": "white", "cost": [3, 0, 0, 0, 7]},                                          
	"16": {"score": 4, "color": "blue", "cost": [7, 0, 0, 0, 0]},                                          
	"17": {"score": 3, "color": "red", "cost": [3, 5, 3, 0, 3]},                                          
	"18": {"score": 3, "color": "white", "cost": [0, 3, 3, 5, 3]},                                          
	"19": {"score": 3, "color": "blue", "cost": [3, 0, 3, 3, 5]}
}
